dataset:
  batch_size: 64
  distance_frac: 12
  train:
    n_samples: 20_000
    seed: 0
  test:
    n_samples: 5_000
    seed: 1

diffusion:
  T: 50
  hidden_dim: 64

optimizer:
  lr: 1e-4

trainer:
  log_every: 50
  log_dir: results
  n_iters: 20_000
    